/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'interactive-features',
    {
      type: 'category',
      label: '🏁 Start Here',
      items: ['intro'],
      collapsed: false,
    },
    {
      type: 'category',
      label: '🔌 Layer 2 (Switching)',
      items: ['ARP', 'VLAN', 'VLAN_Explain', 'STP RSTP MSTP', 'STP_Explain', 'NAT'],
    },
    {
      type: 'category',
      label: '🌐 Layer 3 (Routing)',
      items: ['IPv4', 'IPv6', 'OSPF', 'OSPF_Explain', 'BGP', 'BGP_Explain', 'LifeOfAPacket', 'MPLS'],
    },
    {
      type: 'category',
      label: '🚚 Transport & Services',
      items: ['TCP-UDP', 'DHCP', 'DNS'], // Verified: TCP-UDP.md has id 'TCP UDP'
    },
    {
      type: 'category',
      label: '🐍 Automation',
      items: ['Python-Fundamental', 'Python'], // Verified: PythonFundamental.md has id 'Python Fundamental'
    },
    {
      type: 'category',
      label: '💼 Interview Prep',
      items: ['FAANG-Style', 'Question Bank', 'Guideline-ID'], // Verified IDs
    },
  ],
};

export default sidebars;
